# Generated by Django 3.1.1 on 2021-06-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('SUNDAY', 'Domingo'), ('MONDAY', 'Segunda-Feira'), ('TUESDAY', 'Terça-Feira'), ('WEDNESDAY', 'Quarta-Feira'), ('THURSDAY', 'Quinta-Feira'), ('FRIDAY', 'Seixta-Feira'), ('SATURDAY', 'Sábado')], default='MONDAY', max_length=32)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Data e hora de início')),
                ('end_time', models.DateTimeField(verbose_name='Data e hora de fim')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='schedule.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Intervalo',
                'verbose_name_plural': 'Intervalos',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='schedule.schedule', verbose_name='Agenda'),
        ),
    ]
