# Generated by Django 3.1.1 on 2021-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('SUNDAY', 'Domingo'), ('MONDAY', 'Segunda-Feira'), ('TUESDAY', 'Terça-Feira'), ('WEDNESDAY', 'Quarta-Feira'), ('THURSDAY', 'Quinta-Feira'), ('FRIDAY', 'Sexta-Feira'), ('SATURDAY', 'Sábado')], default='MONDAY', max_length=32)),
                ('start_time', models.DateTimeField(verbose_name='Data e hora de início')),
                ('end_time', models.DateTimeField(verbose_name='Data e hora de fim')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
