# Generated by Django 3.1.1 on 2021-06-14 03:56

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado às')),
                ('scheduled_to', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('status', models.CharField(choices=[('PROCESSING', 'Em processamento'), ('ACCEPTED', 'Aceito'), ('FINISHED', 'Finalizado'), ('CANCELED', 'Cancelado')], default='PROCESSING', max_length=32)),
                ('pin', models.CharField(blank=True, default=apps.core.utils.create_hash, editable=False, max_length=32, null=True, verbose_name='Pin')),
            ],
            options={
                'verbose_name': 'Meet',
                'verbose_name_plural': 'Meet',
            },
        ),
    ]
