# Generated by Django 3.1.1 on 2021-06-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telehealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='meet',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrião'),
        ),
        migrations.AddField(
            model_name='meet',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddConstraint(
            model_name='meet',
            constraint=models.UniqueConstraint(fields=('pin',), name='unique pin'),
        ),
    ]
