# Generated by Django 3.1.1 on 2021-07-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0002_auto_20210628_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='closed_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atendido em: '),
        ),
    ]
